site_name: hypot Package Documentation

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder

nav:
  - Home page: index.md
  - API Reference: api_ref.md