# Workflow to automatically deploy mkdocs website when changes are pushed to main
name: mkdocs-action
on:
  push:
    branches:
      - main  # the workflow will run when you push changes to the main branch
  workflow_dispatch:  # you can also manually trigger the workflow for a different branch
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest  # the action runs on a virtual ubuntu machine
    steps:
- name: Checkout 
        uses: actions/checkout@v2
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest' # option
          #mkdocs_version: '1.1' # option
          requirements: 'requirements.txt' # option
          configfile: 'mkdocs.yml' # option
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site